
ALTER TABLE DEPARTMAN
ADD CONSTRAINT FK_DEPARTMAN_HASTANE
FOREIGN KEY (h_id) REFERENCES HASTANE(h_id);

ALTER TABLE TIBBI_TEKNOLOJI
ADD CONSTRAINT FK_TIBBI_HASTANE
FOREIGN KEY (h_id) REFERENCES HASTANE(h_id);

ALTER TABLE PERSONEL
ADD CONSTRAINT FK_PERSONEL_DEPARTMAN
FOREIGN KEY (d_id) REFERENCES DEPARTMAN(d_id);

ALTER TABLE DOKTOR
ADD CONSTRAINT FK_DOKTOR_POLIKLINIK
FOREIGN KEY (pol_id) REFERENCES POLIKLINIK(pol_id);

ALTER TABLE RANDEVU
ADD CONSTRAINT FK_RANDEVU_DOKTOR
FOREIGN KEY (dr_id) REFERENCES DOKTOR(dr_id);

ALTER TABLE RECETE
ADD CONSTRAINT FK_RECETE_RANDEVU
FOREIGN KEY (r_id) REFERENCES RANDEVU(r_id);

ALTER TABLE ISLEMLER
ADD CONSTRAINT FK_ISLEMLER_RANDEVU
FOREIGN KEY (r_id) REFERENCES RANDEVU(r_id);

ALTER TABLE MEDIKAL_EKIPMAN
ADD CONSTRAINT FK_EKIPMAN_DEPARTMAN
FOREIGN KEY (d_id) REFERENCES DEPARTMAN(d_id);

ALTER TABLE BLOG_YAZİ
ADD CONSTRAINT FK_BLOG_DOKTOR
FOREIGN KEY (dr_id) REFERENCES DOKTOR(dr_id);
