CREATE INDEX IDX_DEPARTMAN_HID ON DEPARTMAN(h_id);
CREATE INDEX IDX_TIBBI_HID ON TIBBI_TEKNOLOJI(h_id);
CREATE INDEX IDX_PERSONEL_DID ON PERSONEL(d_id);
CREATE INDEX IDX_DOKTOR_POLID ON DOKTOR(pol_id);
CREATE INDEX IDX_RANDEVU_DRID ON RANDEVU(dr_id);
CREATE INDEX IDX_RECETE_RID ON RECETE(r_id);
CREATE INDEX IDX_ISLEMLER_RID ON ISLEMLER(r_id);
CREATE INDEX IDX_EKIPMAN_DID ON MEDIKAL_EKIPMAN(d_id);
CREATE INDEX IDX_BLOG_DRID ON BLOG_YAZİ(dr_id);

CREATE INDEX IDX_RANDEVU_DR_TARIH ON RANDEVU(dr_id, r_tarih);
CREATE INDEX IDX_DOKTOR_AD_UZMANLIK ON DOKTOR(dr_adi, uzmanlik);
CREATE INDEX IDX_HASTA_AD_DOGUM ON HASTA(p_adi, p_dogum);

