-- ===========================
-- 1) PKG_HASTANE
-- ===========================

CREATE OR REPLACE PACKAGE PKG_HASTANE AS
    PROCEDURE SP_EKLE(P_ADI IN VARCHAR2, P_ADRESI IN VARCHAR2, P_TEL IN VARCHAR2, P_VERGINO IN VARCHAR2, P_ID OUT NUMBER);
    PROCEDURE SP_GUNCELLE(P_ID IN NUMBER, P_ADI IN VARCHAR2, P_ADRESI IN VARCHAR2, P_TEL IN VARCHAR2, P_VERGINO IN VARCHAR2);
    PROCEDURE SP_SIL(P_ID IN NUMBER);
    PROCEDURE SP_TEKRAR_SIL;
END PKG_HASTANE;
/

CREATE OR REPLACE PACKAGE BODY PKG_HASTANE AS
    PROCEDURE SP_EKLE(P_ADI IN VARCHAR2, P_ADRESI IN VARCHAR2, P_TEL IN VARCHAR2, P_VERGINO IN VARCHAR2, P_ID OUT NUMBER) IS
    BEGIN
        IF P_ADI IS NULL THEN RAISE_APPLICATION_ERROR(-20001, 'Hastane adı boş olamaz.'); END IF;
        P_ID := SEQ_HASTANE.NEXTVAL;
        INSERT INTO HASTANE(h_id, h_adi, h_adresi, h_tel, h_vergino) VALUES (P_ID, P_ADI, P_ADRESI, P_TEL, P_VERGINO);
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Hastane eklendi. ID: ' || P_ID);
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;

    PROCEDURE SP_GUNCELLE(P_ID IN NUMBER, P_ADI IN VARCHAR2, P_ADRESI IN VARCHAR2, P_TEL IN VARCHAR2, P_VERGINO IN VARCHAR2) IS
        V_SAYI NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_SAYI FROM HASTANE WHERE h_id = P_ID;
        IF V_SAYI = 0 THEN RAISE_APPLICATION_ERROR(-20002, 'Hastane bulunamadı.'); END IF;
        UPDATE HASTANE SET h_adi = P_ADI, h_adresi = P_ADRESI, h_tel = P_TEL, h_vergino = P_VERGINO WHERE h_id = P_ID;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Hastane güncellendi.');
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;

    PROCEDURE SP_SIL(P_ID IN NUMBER) IS
        V_SAYI NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_SAYI FROM HASTANE WHERE h_id = P_ID;
        IF V_SAYI = 0 THEN RAISE_APPLICATION_ERROR(-20003, 'Hastane bulunamadı.'); END IF;
        DELETE FROM HASTANE WHERE h_id = P_ID;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Hastane silindi.');
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;

    PROCEDURE SP_TEKRAR_SIL IS
        V_S NUMBER := 0;
    BEGIN
        DELETE FROM HASTANE WHERE h_id NOT IN (SELECT MIN(h_id) FROM HASTANE GROUP BY h_adi, h_vergino);
        V_S := SQL%ROWCOUNT;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Tekrar eden ' || V_S || ' kayıt silindi.');
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;
END PKG_HASTANE;
/




-- ============================================
-- 2) PKG_DEPARTMAN
-- ============================================
CREATE OR REPLACE PACKAGE PKG_DEPARTMAN AS
    PROCEDURE SP_EKLE(P_HID IN NUMBER, P_ADI IN VARCHAR2, P_KONUM IN VARCHAR2, P_BUTCE IN NUMBER, P_ID OUT NUMBER);
    PROCEDURE SP_GUNCELLE(P_ID IN NUMBER, P_HID IN NUMBER, P_ADI IN VARCHAR2, P_KONUM IN VARCHAR2, P_BUTCE IN NUMBER);
    PROCEDURE SP_SIL(P_ID IN NUMBER);
    PROCEDURE SP_TEKRAR_SIL;
END PKG_DEPARTMAN;
/

CREATE OR REPLACE PACKAGE BODY PKG_DEPARTMAN AS
    PROCEDURE SP_EKLE(P_HID IN NUMBER, P_ADI IN VARCHAR2, P_KONUM IN VARCHAR2, P_BUTCE IN NUMBER, P_ID OUT NUMBER) IS
    BEGIN
        IF P_ADI IS NULL THEN RAISE_APPLICATION_ERROR(-20001, 'Departman adı boş olamaz.'); END IF;
        P_ID := SEQ_DEPARTMAN.NEXTVAL;
        INSERT INTO DEPARTMAN(d_id, h_id, d_adi, d_konum, d_butce) VALUES (P_ID, P_HID, P_ADI, P_KONUM, P_BUTCE);
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Departman eklendi. ID: ' || P_ID);
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;

    PROCEDURE SP_GUNCELLE(P_ID IN NUMBER, P_HID IN NUMBER, P_ADI IN VARCHAR2, P_KONUM IN VARCHAR2, P_BUTCE IN NUMBER) IS
        V_SAYI NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_SAYI FROM DEPARTMAN WHERE d_id = P_ID;
        IF V_SAYI = 0 THEN RAISE_APPLICATION_ERROR(-20002, 'Departman bulunamadı.'); END IF;
        UPDATE DEPARTMAN SET h_id = P_HID, d_adi = P_ADI, d_konum = P_KONUM, d_butce = P_BUTCE WHERE d_id = P_ID;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Departman güncellendi.');
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;

    PROCEDURE SP_SIL(P_ID IN NUMBER) IS
        V_SAYI NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_SAYI FROM DEPARTMAN WHERE d_id = P_ID;
        IF V_SAYI = 0 THEN RAISE_APPLICATION_ERROR(-20003, 'Departman bulunamadı.'); END IF;
        DELETE FROM DEPARTMAN WHERE d_id = P_ID;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Departman silindi.');
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;

    PROCEDURE SP_TEKRAR_SIL IS
        V_S NUMBER := 0;
    BEGIN
        DELETE FROM DEPARTMAN WHERE d_id NOT IN (SELECT MIN(d_id) FROM DEPARTMAN GROUP BY h_id, d_adi);
        V_S := SQL%ROWCOUNT;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Tekrar eden ' || V_S || ' kayıt silindi.');
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;
END PKG_DEPARTMAN;
/

-- ============================================
-- 3) PKG_POLIKLINIK
-- ============================================
CREATE OR REPLACE PACKAGE PKG_POLIKLINIK AS
    PROCEDURE SP_EKLE(P_ADI IN VARCHAR2, P_NO IN VARCHAR2, P_KONUM IN VARCHAR2, P_KAPASITE IN NUMBER, P_ID OUT NUMBER);
    PROCEDURE SP_GUNCELLE(P_ID IN NUMBER, P_ADI IN VARCHAR2, P_NO IN VARCHAR2, P_KONUM IN VARCHAR2, P_KAPASITE IN NUMBER);
    PROCEDURE SP_SIL(P_ID IN NUMBER);
    PROCEDURE SP_TEKRAR_SIL;
END PKG_POLIKLINIK;
/

CREATE OR REPLACE PACKAGE BODY PKG_POLIKLINIK AS
    PROCEDURE SP_EKLE(P_ADI IN VARCHAR2, P_NO IN VARCHAR2, P_KONUM IN VARCHAR2, P_KAPASITE IN NUMBER, P_ID OUT NUMBER) IS
    BEGIN
        IF P_ADI IS NULL THEN RAISE_APPLICATION_ERROR(-20001, 'Poliklinik adı boş olamaz.'); END IF;
        P_ID := SEQ_POLIKLINIK.NEXTVAL;
        INSERT INTO POLIKLINIK(pol_id, pol_adi, pol_no, pol_konum, kapasite) VALUES (P_ID, P_ADI, P_NO, P_KONUM, P_KAPASITE);
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Poliklinik eklendi. ID: ' || P_ID);
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;

    PROCEDURE SP_GUNCELLE(P_ID IN NUMBER, P_ADI IN VARCHAR2, P_NO IN VARCHAR2, P_KONUM IN VARCHAR2, P_KAPASITE IN NUMBER) IS
        V_SAYI NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_SAYI FROM POLIKLINIK WHERE pol_id = P_ID;
        IF V_SAYI = 0 THEN RAISE_APPLICATION_ERROR(-20002, 'Poliklinik bulunamadı.'); END IF;
        UPDATE POLIKLINIK SET pol_adi = P_ADI, pol_no = P_NO, pol_konum = P_KONUM, kapasite = P_KAPASITE WHERE pol_id = P_ID;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Poliklinik güncellendi.');
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;

    PROCEDURE SP_SIL(P_ID IN NUMBER) IS
        V_SAYI NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_SAYI FROM POLIKLINIK WHERE pol_id = P_ID;
        IF V_SAYI = 0 THEN RAISE_APPLICATION_ERROR(-20003, 'Poliklinik bulunamadı.'); END IF;
        DELETE FROM POLIKLINIK WHERE pol_id = P_ID;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Poliklinik silindi.');
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;

    PROCEDURE SP_TEKRAR_SIL IS
        V_S NUMBER := 0;
    BEGIN
        DELETE FROM POLIKLINIK WHERE pol_id NOT IN (SELECT MIN(pol_id) FROM POLIKLINIK GROUP BY pol_adi, pol_no);
        V_S := SQL%ROWCOUNT;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Tekrar eden ' || V_S || ' kayıt silindi.');
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;
END PKG_POLIKLINIK;
/


-- ============================================
-- 4) PKG_TIBBI_TEKNOLOJI
-- ============================================
CREATE OR REPLACE PACKAGE PKG_TIBBI_TEKNOLOJI AS
    PROCEDURE SP_EKLE(P_HID IN NUMBER, P_ADI IN VARCHAR2, P_TUR IN VARCHAR2, P_ID OUT NUMBER);
    PROCEDURE SP_GUNCELLE(P_ID IN NUMBER, P_HID IN NUMBER, P_ADI IN VARCHAR2, P_TUR IN VARCHAR2);
    PROCEDURE SP_SIL(P_ID IN NUMBER);
    PROCEDURE SP_TEKRAR_SIL;
END PKG_TIBBI_TEKNOLOJI;
/

CREATE OR REPLACE PACKAGE BODY PKG_TIBBI_TEKNOLOJI AS
    PROCEDURE SP_EKLE(P_HID IN NUMBER, P_ADI IN VARCHAR2, P_TUR IN VARCHAR2, P_ID OUT NUMBER) IS
    BEGIN
        IF P_ADI IS NULL THEN RAISE_APPLICATION_ERROR(-20001, 'Teknoloji adı boş olamaz.'); END IF;
        P_ID := SEQ_TIBBI_TEKNOLOJI.NEXTVAL;
        INSERT INTO TIBBI_TEKNOLOJI(t_id, h_id, t_adi, t_tur) VALUES (P_ID, P_HID, P_ADI, P_TUR);
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Teknoloji eklendi. ID: ' || P_ID);
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;

    PROCEDURE SP_GUNCELLE(P_ID IN NUMBER, P_HID IN NUMBER, P_ADI IN VARCHAR2, P_TUR IN VARCHAR2) IS
        V_SAYI NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_SAYI FROM TIBBI_TEKNOLOJI WHERE t_id = P_ID;
        IF V_SAYI = 0 THEN RAISE_APPLICATION_ERROR(-20002, 'Teknoloji bulunamadı.'); END IF;
        UPDATE TIBBI_TEKNOLOJI SET h_id = P_HID, t_adi = P_ADI, t_tur = P_TUR WHERE t_id = P_ID;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Teknoloji güncellendi.');
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;

    PROCEDURE SP_SIL(P_ID IN NUMBER) IS
        V_SAYI NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_SAYI FROM TIBBI_TEKNOLOJI WHERE t_id = P_ID;
        IF V_SAYI = 0 THEN RAISE_APPLICATION_ERROR(-20003, 'Teknoloji bulunamadı.'); END IF;
        DELETE FROM TIBBI_TEKNOLOJI WHERE t_id = P_ID;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Teknoloji silindi.');
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;

    PROCEDURE SP_TEKRAR_SIL IS
        V_S NUMBER := 0;
    BEGIN
        DELETE FROM TIBBI_TEKNOLOJI WHERE t_id NOT IN (SELECT MIN(t_id) FROM TIBBI_TEKNOLOJI GROUP BY h_id, t_adi);
        V_S := SQL%ROWCOUNT;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Tekrar eden ' || V_S || ' kayıt silindi.');
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;
END PKG_TIBBI_TEKNOLOJI;
/


-- ============================================
-- 5) PKG_PERSONEL
-- ============================================
CREATE OR REPLACE PACKAGE PKG_PERSONEL AS
    PROCEDURE SP_EKLE(P_DID IN NUMBER, P_ADI IN VARCHAR2, P_UNVAN IN VARCHAR2, P_ILETISIM IN VARCHAR2, P_ID OUT NUMBER);
    PROCEDURE SP_GUNCELLE(P_ID IN NUMBER, P_DID IN NUMBER, P_ADI IN VARCHAR2, P_UNVAN IN VARCHAR2, P_ILETISIM IN VARCHAR2);
    PROCEDURE SP_SIL(P_ID IN NUMBER);
    PROCEDURE SP_TEKRAR_SIL;
END PKG_PERSONEL;
/

CREATE OR REPLACE PACKAGE BODY PKG_PERSONEL AS
    PROCEDURE SP_EKLE(P_DID IN NUMBER, P_ADI IN VARCHAR2, P_UNVAN IN VARCHAR2, P_ILETISIM IN VARCHAR2, P_ID OUT NUMBER) IS
    BEGIN
        IF P_ADI IS NULL THEN RAISE_APPLICATION_ERROR(-20001, 'Personel adı boş olamaz.'); END IF;
        P_ID := SEQ_PERSONEL.NEXTVAL;
        INSERT INTO PERSONEL(s_id, d_id, s_adi, s_unvan, s_iletisim) VALUES (P_ID, P_DID, P_ADI, P_UNVAN, P_ILETISIM);
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Personel eklendi. ID: ' || P_ID);
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;

    PROCEDURE SP_GUNCELLE(P_ID IN NUMBER, P_DID IN NUMBER, P_ADI IN VARCHAR2, P_UNVAN IN VARCHAR2, P_ILETISIM IN VARCHAR2) IS
        V_SAYI NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_SAYI FROM PERSONEL WHERE s_id = P_ID;
        IF V_SAYI = 0 THEN RAISE_APPLICATION_ERROR(-20002, 'Personel bulunamadı.'); END IF;
        UPDATE PERSONEL SET d_id = P_DID, s_adi = P_ADI, s_unvan = P_UNVAN, s_iletisim = P_ILETISIM WHERE s_id = P_ID;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Personel güncellendi.');
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;

    PROCEDURE SP_SIL(P_ID IN NUMBER) IS
        V_SAYI NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_SAYI FROM PERSONEL WHERE s_id = P_ID;
        IF V_SAYI = 0 THEN RAISE_APPLICATION_ERROR(-20003, 'Personel bulunamadı.'); END IF;
        DELETE FROM PERSONEL WHERE s_id = P_ID;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Personel silindi.');
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;

    PROCEDURE SP_TEKRAR_SIL IS
        V_S NUMBER := 0;
    BEGIN
        DELETE FROM PERSONEL WHERE s_id NOT IN (SELECT MIN(s_id) FROM PERSONEL GROUP BY s_adi, s_iletisim);
        V_S := SQL%ROWCOUNT;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Tekrar eden ' || V_S || ' kayıt silindi.');
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;
END PKG_PERSONEL;
/


-- ============================================
-- 6) PKG_DOKTOR
-- ============================================
CREATE OR REPLACE PACKAGE PKG_DOKTOR AS
    PROCEDURE SP_EKLE(P_POLID IN NUMBER, P_ADI IN VARCHAR2, P_UZMANLIK IN VARCHAR2, P_TC IN VARCHAR2, P_ILETISIM IN VARCHAR2, P_ID OUT NUMBER);
    PROCEDURE SP_GUNCELLE(P_ID IN NUMBER, P_POLID IN NUMBER, P_ADI IN VARCHAR2, P_UZMANLIK IN VARCHAR2, P_TC IN VARCHAR2, P_ILETISIM IN VARCHAR2);
    PROCEDURE SP_SIL(P_ID IN NUMBER);
    PROCEDURE SP_TEKRAR_SIL;
END PKG_DOKTOR;
/

CREATE OR REPLACE PACKAGE BODY PKG_DOKTOR AS
    PROCEDURE SP_EKLE(P_POLID IN NUMBER, P_ADI IN VARCHAR2, P_UZMANLIK IN VARCHAR2, P_TC IN VARCHAR2, P_ILETISIM IN VARCHAR2, P_ID OUT NUMBER) IS
    BEGIN
        IF LENGTH(P_TC) != 11 THEN RAISE_APPLICATION_ERROR(-20001, 'TC 11 haneli olmalıdır.'); END IF;
        IF P_ADI IS NULL THEN RAISE_APPLICATION_ERROR(-20002, 'Doktor adı boş olamaz.'); END IF;
        P_ID := SEQ_DOKTOR.NEXTVAL;
        INSERT INTO DOKTOR(dr_id, pol_id, dr_adi, uzmanlik, tc_no, dr_iletisim) VALUES (P_ID, P_POLID, P_ADI, P_UZMANLIK, P_TC, P_ILETISIM);
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Doktor eklendi. ID: ' || P_ID);
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;

    PROCEDURE SP_GUNCELLE(P_ID IN NUMBER, P_POLID IN NUMBER, P_ADI IN VARCHAR2, P_UZMANLIK IN VARCHAR2, P_TC IN VARCHAR2, P_ILETISIM IN VARCHAR2) IS
        V_SAYI NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_SAYI FROM DOKTOR WHERE dr_id = P_ID;
        IF V_SAYI = 0 THEN RAISE_APPLICATION_ERROR(-20003, 'Doktor bulunamadı.'); END IF;
        UPDATE DOKTOR SET pol_id = P_POLID, dr_adi = P_ADI, uzmanlik = P_UZMANLIK, tc_no = P_TC, dr_iletisim = P_ILETISIM WHERE dr_id = P_ID;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Doktor güncellendi.');
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;

    PROCEDURE SP_SIL(P_ID IN NUMBER) IS
        V_SAYI NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_SAYI FROM DOKTOR WHERE dr_id = P_ID;
        IF V_SAYI = 0 THEN RAISE_APPLICATION_ERROR(-20004, 'Doktor bulunamadı.'); END IF;
        DELETE FROM DOKTOR WHERE dr_id = P_ID;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Doktor silindi.');
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;

    PROCEDURE SP_TEKRAR_SIL IS
        V_S NUMBER := 0;
    BEGIN
        DELETE FROM DOKTOR WHERE dr_id NOT IN (SELECT MIN(dr_id) FROM DOKTOR GROUP BY tc_no);
        V_S := SQL%ROWCOUNT;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Tekrar eden ' || V_S || ' kayıt silindi.');
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;
END PKG_DOKTOR;
/



-- ============================================
-- 7) PKG_RANDEVU
-- ============================================
CREATE OR REPLACE PACKAGE PKG_RANDEVU AS
    PROCEDURE SP_EKLE(P_DRID IN NUMBER, P_TARIH IN DATE, P_DURUM IN VARCHAR2, P_ID OUT NUMBER);
    PROCEDURE SP_GUNCELLE(P_ID IN NUMBER, P_DRID IN NUMBER, P_TARIH IN DATE, P_DURUM IN VARCHAR2);
    PROCEDURE SP_SIL(P_ID IN NUMBER);
    PROCEDURE SP_TEKRAR_SIL;
END PKG_RANDEVU;
/

CREATE OR REPLACE PACKAGE BODY PKG_RANDEVU AS
    PROCEDURE SP_EKLE(P_DRID IN NUMBER, P_TARIH IN DATE, P_DURUM IN VARCHAR2, P_ID OUT NUMBER) IS
    BEGIN
        IF P_TARIH IS NULL THEN RAISE_APPLICATION_ERROR(-20001, 'Randevu tarihi boş olamaz.'); END IF;
        P_ID := SEQ_RANDEVU.NEXTVAL;
        INSERT INTO RANDEVU(r_id, dr_id, r_tarih, r_durum) VALUES (P_ID, P_DRID, P_TARIH, NVL(P_DURUM, 'Bekliyor'));
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Randevu eklendi. ID: ' || P_ID);
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;

    PROCEDURE SP_GUNCELLE(P_ID IN NUMBER, P_DRID IN NUMBER, P_TARIH IN DATE, P_DURUM IN VARCHAR2) IS
        V_SAYI NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_SAYI FROM RANDEVU WHERE r_id = P_ID;
        IF V_SAYI = 0 THEN RAISE_APPLICATION_ERROR(-20002, 'Randevu bulunamadı.'); END IF;
        UPDATE RANDEVU SET dr_id = P_DRID, r_tarih = P_TARIH, r_durum = P_DURUM WHERE r_id = P_ID;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Randevu güncellendi.');
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;

    PROCEDURE SP_SIL(P_ID IN NUMBER) IS
        V_SAYI NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_SAYI FROM RANDEVU WHERE r_id = P_ID;
        IF V_SAYI = 0 THEN RAISE_APPLICATION_ERROR(-20003, 'Randevu bulunamadı.'); END IF;
        DELETE FROM RANDEVU WHERE r_id = P_ID;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Randevu silindi.');
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;

    PROCEDURE SP_TEKRAR_SIL IS
        V_S NUMBER := 0;
    BEGIN
        DELETE FROM RANDEVU WHERE r_id NOT IN (SELECT MIN(r_id) FROM RANDEVU GROUP BY dr_id, r_tarih);
        V_S := SQL%ROWCOUNT;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Tekrar eden ' || V_S || ' kayıt silindi.');
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;
END PKG_RANDEVU;
/

-- ============================================
-- 8) PKG_HASTA
-- ============================================
CREATE OR REPLACE PACKAGE PKG_HASTA AS
    PROCEDURE SP_EKLE(P_ADI IN VARCHAR2, P_CINSIYET IN CHAR, P_DOGUM IN DATE, P_ADRES IN VARCHAR2, P_ILETISIM IN VARCHAR2, P_KANGRUBU IN VARCHAR2, P_ID OUT NUMBER);
    PROCEDURE SP_GUNCELLE(P_ID IN NUMBER, P_ADI IN VARCHAR2, P_CINSIYET IN CHAR, P_DOGUM IN DATE, P_ADRES IN VARCHAR2, P_ILETISIM IN VARCHAR2, P_KANGRUBU IN VARCHAR2);
    PROCEDURE SP_SIL(P_ID IN NUMBER);
    PROCEDURE SP_TEKRAR_SIL;
END PKG_HASTA;
/

CREATE OR REPLACE PACKAGE BODY PKG_HASTA AS
    PROCEDURE SP_EKLE(P_ADI IN VARCHAR2, P_CINSIYET IN CHAR, P_DOGUM IN DATE, P_ADRES IN VARCHAR2, P_ILETISIM IN VARCHAR2, P_KANGRUBU IN VARCHAR2, P_ID OUT NUMBER) IS
    BEGIN
        IF P_CINSIYET NOT IN ('E','K') THEN RAISE_APPLICATION_ERROR(-20001, 'Cinsiyet E veya K olmalıdır.'); END IF;
        IF P_ADI IS NULL THEN RAISE_APPLICATION_ERROR(-20002, 'Hasta adı boş olamaz.'); END IF;
        P_ID := SEQ_HASTA.NEXTVAL;
        INSERT INTO HASTA(p_id, p_adi, p_cinsiyet, p_dogum, p_adres, p_iletisim, p_kangrubu) VALUES (P_ID, P_ADI, P_CINSIYET, P_DOGUM, P_ADRES, P_ILETISIM, P_KANGRUBU);
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Hasta eklendi. ID: ' || P_ID);
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;

    PROCEDURE SP_GUNCELLE(P_ID IN NUMBER, P_ADI IN VARCHAR2, P_CINSIYET IN CHAR, P_DOGUM IN DATE, P_ADRES IN VARCHAR2, P_ILETISIM IN VARCHAR2, P_KANGRUBU IN VARCHAR2) IS
        V_SAYI NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_SAYI FROM HASTA WHERE p_id = P_ID;
        IF V_SAYI = 0 THEN RAISE_APPLICATION_ERROR(-20003, 'Hasta bulunamadı.'); END IF;
        UPDATE HASTA SET p_adi = P_ADI, p_cinsiyet = P_CINSIYET, p_dogum = P_DOGUM, p_adres = P_ADRES, p_iletisim = P_ILETISIM, p_kangrubu = P_KANGRUBU WHERE p_id = P_ID;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Hasta güncellendi.');
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;

    PROCEDURE SP_SIL(P_ID IN NUMBER) IS
        V_SAYI NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_SAYI FROM HASTA WHERE p_id = P_ID;
        IF V_SAYI = 0 THEN RAISE_APPLICATION_ERROR(-20004, 'Hasta bulunamadı.'); END IF;
        DELETE FROM HASTA WHERE p_id = P_ID;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Hasta silindi.');
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;

    PROCEDURE SP_TEKRAR_SIL IS
        V_S NUMBER := 0;
    BEGIN
        DELETE FROM HASTA WHERE p_id NOT IN (SELECT MIN(p_id) FROM HASTA GROUP BY p_adi, p_dogum, p_iletisim);
        V_S := SQL%ROWCOUNT;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Tekrar eden ' || V_S || ' kayıt silindi.');
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;
END PKG_HASTA;
/


-- ============================================
-- 9) PKG_RECETE
-- ============================================
CREATE OR REPLACE PACKAGE PKG_RECETE AS
    PROCEDURE SP_EKLE(P_RID IN NUMBER, P_ILAC IN VARCHAR2, P_SURE IN DATE, P_TALIMAT IN VARCHAR2, P_DOZ IN VARCHAR2, P_ID OUT NUMBER);
    PROCEDURE SP_GUNCELLE(P_ID IN NUMBER, P_RID IN NUMBER, P_ILAC IN VARCHAR2, P_SURE IN DATE, P_TALIMAT IN VARCHAR2, P_DOZ IN VARCHAR2);
    PROCEDURE SP_SIL(P_ID IN NUMBER);
    PROCEDURE SP_TEKRAR_SIL;
END PKG_RECETE;
/

CREATE OR REPLACE PACKAGE BODY PKG_RECETE AS
    PROCEDURE SP_EKLE(P_RID IN NUMBER, P_ILAC IN VARCHAR2, P_SURE IN DATE, P_TALIMAT IN VARCHAR2, P_DOZ IN VARCHAR2, P_ID OUT NUMBER) IS
    BEGIN
        IF P_ILAC IS NULL THEN RAISE_APPLICATION_ERROR(-20001, 'İlaç adı boş olamaz.'); END IF;
        P_ID := SEQ_RECETE.NEXTVAL;
        INSERT INTO RECETE(re_id, r_id, ilac_ad, sure, talimat, doz) VALUES (P_ID, P_RID, P_ILAC, P_SURE, P_TALIMAT, P_DOZ);
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Reçete eklendi. ID: ' || P_ID);
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;

    PROCEDURE SP_GUNCELLE(P_ID IN NUMBER, P_RID IN NUMBER, P_ILAC IN VARCHAR2, P_SURE IN DATE, P_TALIMAT IN VARCHAR2, P_DOZ IN VARCHAR2) IS
        V_SAYI NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_SAYI FROM RECETE WHERE re_id = P_ID;
        IF V_SAYI = 0 THEN RAISE_APPLICATION_ERROR(-20002, 'Reçete bulunamadı.'); END IF;
        UPDATE RECETE SET r_id = P_RID, ilac_ad = P_ILAC, sure = P_SURE, talimat = P_TALIMAT, doz = P_DOZ WHERE re_id = P_ID;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Reçete güncellendi.');
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;

    PROCEDURE SP_SIL(P_ID IN NUMBER) IS
        V_SAYI NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_SAYI FROM RECETE WHERE re_id = P_ID;
        IF V_SAYI = 0 THEN RAISE_APPLICATION_ERROR(-20003, 'Reçete bulunamadı.'); END IF;
        DELETE FROM RECETE WHERE re_id = P_ID;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Reçete silindi.');
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;

    PROCEDURE SP_TEKRAR_SIL IS
        V_S NUMBER := 0;
    BEGIN
        DELETE FROM RECETE WHERE re_id NOT IN (SELECT MIN(re_id) FROM RECETE GROUP BY r_id, ilac_ad, doz);
        V_S := SQL%ROWCOUNT;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Tekrar eden ' || V_S || ' kayıt silindi.');
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;
END PKG_RECETE;
/

-- ============================================
-- 10) PKG_ODEME
-- ============================================
CREATE OR REPLACE PACKAGE PKG_ODEME AS
    PROCEDURE SP_EKLE(P_YONTEM IN VARCHAR2, P_ONAY IN VARCHAR2, P_EVRAK IN NUMBER, P_TUTAR IN NUMBER, P_TARIH IN DATE, P_ID OUT NUMBER);
    PROCEDURE SP_GUNCELLE(P_ID IN NUMBER, P_YONTEM IN VARCHAR2, P_ONAY IN VARCHAR2, P_EVRAK IN NUMBER, P_TUTAR IN NUMBER, P_TARIH IN DATE);
    PROCEDURE SP_SIL(P_ID IN NUMBER);
    PROCEDURE SP_TEKRAR_SIL;
END PKG_ODEME;
/

CREATE OR REPLACE PACKAGE BODY PKG_ODEME AS
    PROCEDURE SP_EKLE(P_YONTEM IN VARCHAR2, P_ONAY IN VARCHAR2, P_EVRAK IN NUMBER, P_TUTAR IN NUMBER, P_TARIH IN DATE, P_ID OUT NUMBER) IS
    BEGIN
        IF P_YONTEM IS NULL THEN RAISE_APPLICATION_ERROR(-20001, 'Ödeme yöntemi boş olamaz.'); END IF;
        IF P_TUTAR < 0 THEN RAISE_APPLICATION_ERROR(-20002, 'Tutar negatif olamaz.'); END IF;
        P_ID := SEQ_ODEME.NEXTVAL;
        INSERT INTO ODEME(fatura_id, o_yontem, onay, evrak_no, tutar, o_tarih) VALUES (P_ID, P_YONTEM, P_ONAY, P_EVRAK, P_TUTAR, P_TARIH);
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Ödeme eklendi. ID: ' || P_ID);
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;

    PROCEDURE SP_GUNCELLE(P_ID IN NUMBER, P_YONTEM IN VARCHAR2, P_ONAY IN VARCHAR2, P_EVRAK IN NUMBER, P_TUTAR IN NUMBER, P_TARIH IN DATE) IS
        V_SAYI NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_SAYI FROM ODEME WHERE fatura_id = P_ID;
        IF V_SAYI = 0 THEN RAISE_APPLICATION_ERROR(-20003, 'Ödeme bulunamadı.'); END IF;
        UPDATE ODEME SET o_yontem = P_YONTEM, onay = P_ONAY, evrak_no = P_EVRAK, tutar = P_TUTAR, o_tarih = P_TARIH WHERE fatura_id = P_ID;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Ödeme güncellendi.');
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;

    PROCEDURE SP_SIL(P_ID IN NUMBER) IS
        V_SAYI NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_SAYI FROM ODEME WHERE fatura_id = P_ID;
        IF V_SAYI = 0 THEN RAISE_APPLICATION_ERROR(-20004, 'Ödeme bulunamadı.'); END IF;
        DELETE FROM ODEME WHERE fatura_id = P_ID;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Ödeme silindi.');
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;

    PROCEDURE SP_TEKRAR_SIL IS
        V_S NUMBER := 0;
    BEGIN
        DELETE FROM ODEME WHERE fatura_id NOT IN (SELECT MIN(fatura_id) FROM ODEME GROUP BY evrak_no, tutar, o_tarih);
        V_S := SQL%ROWCOUNT;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Tekrar eden ' || V_S || ' kayıt silindi.');
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;
END PKG_ODEME;
/


-- ============================================
-- 11) PKG_ISLEMLER
-- ============================================
CREATE OR REPLACE PACKAGE PKG_ISLEMLER AS
    PROCEDURE SP_EKLE(P_RID IN NUMBER, P_TUR IN VARCHAR2, P_ID OUT NUMBER);
    PROCEDURE SP_GUNCELLE(P_ID IN NUMBER, P_RID IN NUMBER, P_TUR IN VARCHAR2);
    PROCEDURE SP_SIL(P_ID IN NUMBER);
    PROCEDURE SP_TEKRAR_SIL;
END PKG_ISLEMLER;
/

CREATE OR REPLACE PACKAGE BODY PKG_ISLEMLER AS
    PROCEDURE SP_EKLE(P_RID IN NUMBER, P_TUR IN VARCHAR2, P_ID OUT NUMBER) IS
    BEGIN
        IF P_TUR IS NULL THEN RAISE_APPLICATION_ERROR(-20001, 'İşlem türü boş olamaz.'); END IF;
        P_ID := SEQ_ISLEMLER.NEXTVAL;
        INSERT INTO ISLEMLER(islem_id, r_id, islem_turu) VALUES (P_ID, P_RID, P_TUR);
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('İşlem eklendi. ID: ' || P_ID);
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;

    PROCEDURE SP_GUNCELLE(P_ID IN NUMBER, P_RID IN NUMBER, P_TUR IN VARCHAR2) IS
        V_SAYI NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_SAYI FROM ISLEMLER WHERE islem_id = P_ID;
        IF V_SAYI = 0 THEN RAISE_APPLICATION_ERROR(-20002, 'İşlem bulunamadı.'); END IF;
        UPDATE ISLEMLER SET r_id = P_RID, islem_turu = P_TUR WHERE islem_id = P_ID;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('İşlem güncellendi.');
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;

    PROCEDURE SP_SIL(P_ID IN NUMBER) IS
        V_SAYI NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_SAYI FROM ISLEMLER WHERE islem_id = P_ID;
        IF V_SAYI = 0 THEN RAISE_APPLICATION_ERROR(-20003, 'İşlem bulunamadı.'); END IF;
        DELETE FROM ISLEMLER WHERE islem_id = P_ID;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('İşlem silindi.');
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;

    PROCEDURE SP_TEKRAR_SIL IS
        V_S NUMBER := 0;
    BEGIN
        DELETE FROM ISLEMLER WHERE islem_id NOT IN (SELECT MIN(islem_id) FROM ISLEMLER GROUP BY r_id, islem_turu);
        V_S := SQL%ROWCOUNT;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Tekrar eden ' || V_S || ' kayıt silindi.');
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;
END PKG_ISLEMLER;
/

-- ============================================
-- 12) PKG_MEDIKAL_EKIPMAN
-- ============================================
CREATE OR REPLACE PACKAGE PKG_MEDIKAL_EKIPMAN AS
    PROCEDURE SP_EKLE(P_DID IN NUMBER, P_AD IN VARCHAR2, P_BAKIM IN VARCHAR2, P_ID OUT NUMBER);
    PROCEDURE SP_GUNCELLE(P_ID IN NUMBER, P_DID IN NUMBER, P_AD IN VARCHAR2, P_BAKIM IN VARCHAR2);
    PROCEDURE SP_SIL(P_ID IN NUMBER);
    PROCEDURE SP_TEKRAR_SIL;
END PKG_MEDIKAL_EKIPMAN;
/

CREATE OR REPLACE PACKAGE BODY PKG_MEDIKAL_EKIPMAN AS
    PROCEDURE SP_EKLE(P_DID IN NUMBER, P_AD IN VARCHAR2, P_BAKIM IN VARCHAR2, P_ID OUT NUMBER) IS
    BEGIN
        IF P_AD IS NULL THEN RAISE_APPLICATION_ERROR(-20001, 'Ekipman adı boş olamaz.'); END IF;
        P_ID := SEQ_MEDIKAL_EKIPMAN.NEXTVAL;
        INSERT INTO MEDIKAL_EKIPMAN(ekipman_id, d_id, ekipman_ad, bakim) VALUES (P_ID, P_DID, P_AD, P_BAKIM);
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Ekipman eklendi. ID: ' || P_ID);
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;

    PROCEDURE SP_GUNCELLE(P_ID IN NUMBER, P_DID IN NUMBER, P_AD IN VARCHAR2, P_BAKIM IN VARCHAR2) IS
        V_SAYI NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_SAYI FROM MEDIKAL_EKIPMAN WHERE ekipman_id = P_ID;
        IF V_SAYI = 0 THEN RAISE_APPLICATION_ERROR(-20002, 'Ekipman bulunamadı.'); END IF;
        UPDATE MEDIKAL_EKIPMAN SET d_id = P_DID, ekipman_ad = P_AD, bakim = P_BAKIM WHERE ekipman_id = P_ID;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Ekipman güncellendi.');
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;

    PROCEDURE SP_SIL(P_ID IN NUMBER) IS
        V_SAYI NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_SAYI FROM MEDIKAL_EKIPMAN WHERE ekipman_id = P_ID;
        IF V_SAYI = 0 THEN RAISE_APPLICATION_ERROR(-20003, 'Ekipman bulunamadı.'); END IF;
        DELETE FROM MEDIKAL_EKIPMAN WHERE ekipman_id = P_ID;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Ekipman silindi.');
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;

    PROCEDURE SP_TEKRAR_SIL IS
        V_S NUMBER := 0;
    BEGIN
        DELETE FROM MEDIKAL_EKIPMAN WHERE ekipman_id NOT IN (SELECT MIN(ekipman_id) FROM MEDIKAL_EKIPMAN GROUP BY d_id, ekipman_ad);
        V_S := SQL%ROWCOUNT;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Tekrar eden ' || V_S || ' kayıt silindi.');
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;
END PKG_MEDIKAL_EKIPMAN;
/

-- ============================================
-- 13) PKG_BLOG_YAZI
-- ============================================
CREATE OR REPLACE PACKAGE PKG_BLOG_YAZİ AS
    PROCEDURE SP_EKLE(P_DRID IN NUMBER, P_ICERIK IN VARCHAR2, P_BASLIK IN VARCHAR2, P_TARIH IN DATE, P_ID OUT NUMBER);
    PROCEDURE SP_GUNCELLE(P_ID IN NUMBER, P_DRID IN NUMBER, P_ICERIK IN VARCHAR2, P_BASLIK IN VARCHAR2, P_TARIH IN DATE);
    PROCEDURE SP_SIL(P_ID IN NUMBER);
    PROCEDURE SP_TEKRAR_SIL;
END PKG_BLOG_YAZİ;
/

CREATE OR REPLACE PACKAGE BODY PKG_BLOG_YAZİ AS
    PROCEDURE SP_EKLE(P_DRID IN NUMBER, P_ICERIK IN VARCHAR2, P_BASLIK IN VARCHAR2, P_TARIH IN DATE, P_ID OUT NUMBER) IS
    BEGIN
        IF P_BASLIK IS NULL THEN RAISE_APPLICATION_ERROR(-20001, 'Başlık boş olamaz.'); END IF;
        P_ID := SEQ_BLOG_YAZİ.NEXTVAL;
        INSERT INTO BLOG_YAZİ(b_id, dr_id, icerik, baslik, yayin_tarih) VALUES (P_ID, P_DRID, P_ICERIK, P_BASLIK, P_TARIH);
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Blog yazısı eklendi. ID: ' || P_ID);
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;

    PROCEDURE SP_GUNCELLE(P_ID IN NUMBER, P_DRID IN NUMBER, P_ICERIK IN VARCHAR2, P_BASLIK IN VARCHAR2, P_TARIH IN DATE) IS
        V_SAYI NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_SAYI FROM BLOG_YAZİ WHERE b_id = P_ID;
        IF V_SAYI = 0 THEN RAISE_APPLICATION_ERROR(-20002, 'Blog yazısı bulunamadı.'); END IF;
        UPDATE BLOG_YAZİ SET dr_id = P_DRID, icerik = P_ICERIK, baslik = P_BASLIK, yayin_tarih = P_TARIH WHERE b_id = P_ID;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Blog yazısı güncellendi.');
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;

    PROCEDURE SP_SIL(P_ID IN NUMBER) IS
        V_SAYI NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_SAYI FROM BLOG_YAZİ WHERE b_id = P_ID;
        IF V_SAYI = 0 THEN RAISE_APPLICATION_ERROR(-20003, 'Blog yazısı bulunamadı.'); END IF;
        DELETE FROM BLOG_YAZİ WHERE b_id = P_ID;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Blog yazısı silindi.');
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;

    PROCEDURE SP_TEKRAR_SIL IS
        V_S NUMBER := 0;
    BEGIN
        DELETE FROM BLOG_YAZİ WHERE b_id NOT IN (SELECT MIN(b_id) FROM BLOG_YAZİ GROUP BY dr_id, baslik);
        V_S := SQL%ROWCOUNT;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Tekrar eden ' || V_S || ' kayıt silindi.');
    EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('HATA: ' || SQLERRM); RAISE;
    END;
END PKG_BLOG_YAZİ;
/
