
CREATE SEQUENCE SEQ_HASTANE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DEPARTMAN START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_POLIKLINIK START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TIBBI_TEKNOLOJI START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PERSONEL START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DOKTOR START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_RANDEVU START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_HASTA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_RECETE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ODEME START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ISLEMLER START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MEDIKAL_EKIPMAN START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_BLOG_YAZİ START WITH 1 INCREMENT BY 1;
